GET http://localhost:3000/api/questions/5/threads


###
POST http://localhost:3000/api/questions/52/threads
Content-Type: application/json

{
    "thread_id": "",
    "thread_content": "Banana",
    "question_id": 5,
    "id_user": "hyoon"
}

